version: '3.4'

services:
  kaleidocontracttemplates:
    image: kaleidocontracttemplates
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
